bitbuy-infrastructure/bb-cicd

- .github/workflows/reusable-deploy.yaml
- .github/workflows/reusable-docker-build.yaml
- .github/workflows/reusable-docker-tag.yaml
- .github/workflows/reusable-helm-build.yaml
- .github/workflows/reusable-pipeline-params.yaml
- .github/workflows/test-helm.yaml
- .github/workflows/test-snyk-java-11.yaml
- README.md
* <https://bitbuy.atlassian.net/browse/BBSECAWS-404>
* setup reusable pipelines
* setup reusable pipelines
* [outputs]
> BBSECAWS-404 setup reusable pipelines

- .flake8
- .github/workflows/reusable-deploy.yaml
- .github/workflows/reusable-docker-build.yaml
- .github/workflows/reusable-helm-build.yaml
- .github/workflows/test-helm.yaml
- .gitignore
- README.md
- requirements.txt
- src/pipeline.py
- src/readme.md
- values.yaml
* <https://bitbuy.atlassian.net/browse/BBSECAWS-388>
* need a way to merge-common and env vars
* added python to merge-common and env
* added python to update tag in the deployments for argocd
* [outputs]
> BBSECAWS-388

- .github/workflows/reusable-docker-build.yaml
* <https://bitbuy.atlassian.net/browse/BBSECAWS-442>
* Fix docker build expression
* Fix docker build expression
* [outputs]
> Fix docker build expression

- .github/workflows/reusable-helm-build.yaml
* [ie: <https://bitbuy.atlassian.net/browse/BBSECAWS-443>]
* [outputs]
> BBSECAWS-443 update helm check

- .github/workflows/reusable-deploy.yaml
* <https://bitbuy.atlassian.net/browse/BBSECAWS-443>
* Fix commits to microservices from PR
* Fix commits to microservices from PR
* [outputs]
> Fix commits to microservices from PR

- .github/workflows/reusable-docker-build.yaml
Bitbuy maven package is hosted on GitHub, so, it need to add GitHub token to the maven setting during build.
> Add maven repo cred

- .github/workflows/reusable-docker-build.yaml
> add GitHub

- .github/workflows/reusable-deploy.yaml
- .github/workflows/reusable-docker-build.yaml
> fix repo name case and docker tag

- .github/workflows/reusable-docker-build.yaml
> remove redundant check

- .github/workflows/reusable-docker-build.yaml
> repo name correction

- .github/workflows/reusable-helm-build.yaml
- .github/workflows/reusable-test-helm.yaml
> add reusable helm test, push new helm chart on merge

- .github/workflows/reusable-docker-build.yaml
> change submodule secrets to env

- .github/actions/db-migration/action.yaml
- .github/actions/setup-aws-kustomize/action.yaml
- .github/workflows/reusable-db-migration.yaml
- example.job.yaml.tmpl
> introduce flyway db migration

- .github/workflows/reusable-flyway-build.yaml
> create reusable flyway build

- .github/workflows/reusable-docker-build.yaml
> Adding npm rc

- .github/workflows/reusable-publish-java-package.yaml
https://bitbuy.atlassian.net/browse/TIM-594
> TIM-594 add reusable workflow for java packages

- .github/workflows/reusable-publish-java-package.yaml
https://bitbuy.atlassian.net/browse/TIM-594
> TIM-594 make java version configurable

- .github/workflows/reusable-publish-java-package.yaml
Reverts bitbuy-infrastructure/bb-cicd#34
> Revert "Update reusable-publish-java-package.yaml"

- .github/workflows/reusable-docker-build.yaml
- Add codeartifact token to be able to get BCM packages from build actions
> TIM-628 add codeartifact token

- .github/workflows/reusable-docker-build.yaml
> TIM-628 update region

- .github/workflows/reusable-publish-java-package.yaml
- Update protoc version to fix compile errors in bmi-event-browser
> TIM-000 fix protoc version

- .github/workflows/reusable-publish-java-package.yaml
> Remove protobuf-compiler version breaking builds

- .github/workflows/reusable-docker-build.yaml
> fix for npmrc

- .github/workflows/reusable-deploy.yaml
> fix broken workflow

- .github/workflows/reusable-docker-build.yaml
> fixing build cache issue not working

- .github/workflows/reusable-docker-build.yaml
turning cache back on. It was missed from the previous brown out test and fixes
> cache back on

- .github/workflows/reusable-helm-build.yaml
> TAL-502 consolidate skip conditions and add summary
